apiVersion: v1
kind: Pod
metadata:
  name: mondebian
spec:
  containers:
  - name: mondebian
    image: debian
    command: ["/bin/bash", "-c" ,"sleep 600"]
    volumeMounts:
    - name: monvolume
      mountPath: /tmp/
  volumes:
  - name: monvolume
    persistentVolumeClaim:
      claimName: mynfspvc