apiVersion: v1
kind: Pod
metadata:
  name: modbpod
spec:
  containers:
  - name: mondbsql
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    ports:
    - containerPort: 3306
    volumeMounts:
    - name: monvolumesql
      mountPath: /var/lib/mysql
  volumes:
  - name: monvolumesql
    persistentVolumeClaim:
      claimName: mynfspvc