apiVersion: v1
kind: Pod
metadata:
  name: nginx-deploy
spec:
  containers:
  - name: monnginx
    image: nginx
    volumeMounts:
    - name: monvolume
      mountPath: /usr/share/nginx/html
  volumes:
    - name: monvolume
      persistentVolumeClaim:
        claimName: mynfspvc