# Vagrantfile configuration
Vagrant.configure("2") do |config|
  # Configuration commune pour tous les VMs
  common = <<-SHELL
    # Ajouter les nodes et le master dans le fichier hosts
    if ! grep -q deploykub /etc/hosts; then echo "192.168.6.120 deploykub" | sudo tee -a /etc/hosts; fi
    for i in {1..5}; do if ! grep -q node0$i /etc/hosts; then echo "192.168.6.12$i node0$i" | sudo tee -a /etc/hosts; fi; done
    
    # Installation de quelques paquets de base
    sudo apt update && sudo apt install -y vim tree net-tools telnet git python3-pip
    echo "autocmd filetype yaml setlocal ai ts=2 sw=2 et" > /home/vagrant/.vimrc
  SHELL

  config.vm.box = "debian/bullseye64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1536  # Mémoire ajustée pour chaque VM
    v.cpus = 1       # CPU alloué par VM
  end

  # Configuration du Master
  config.vm.define "deploykub" do |deploykub|
    deploykub.vm.hostname = "deploykub"
    deploykub.vm.network "private_network", ip: "192.168.6.120"
    deploykub.vm.provision "shell", inline: common
  end

  # Configuration des Nodes
  (1..5).each do |i|
    config.vm.define "node0#{i}" do |node|
      node.vm.hostname = "node0#{i}"
      node.vm.network "private_network", ip: "192.168.6.12#{i}"
      node.vm.provision "shell", inline: common
    end
  end
end
